{
    {  
        "id" : 0,
        "average_thread_similarity": 0.5270053598552831,
        "comments": [
            "you can check swift 3 at microcenter ( 500$ )  \ncome with 100% srgb screen, i5 12th, should be fine for those task  \ndownside is it cant be upgrade ram, so you are stuck with 8gb   \nand windows 11 are know for being ram hungry",
            "Since you are going to game,  I would recommend  [Acer Swift X]( because  it comes with everything you need, AMD Ryzen 7 5800U Octa-Core CPU, 16GB of ram, good SSD storage of 512GB for faster boot up and loading, 14 inch Full HD IPS  screen,Wi-Fi 6,NVIDIA RTX 3050Ti Laptop GPU, high build quality,  and backlit keyboard, and it's within your budget.\n\nBlack Friday started early this year so make sure to check [My List of Best Laptop Deals on Amazon](\n\n\n\nPlease note I'm using affiliate links which means I'll receive a small percent of the purchase if you use this link at no extra cost to you",
            "For general use and light gaming at this price range,\tI would advise you to check this laptop\n\t\nlaptop name\t| [Acer Swift X]( \n---\t|----\nCPU\t| Octa core Ryzen 5800U\nGPU\t‎| RTX 3050Ti\nScreen\t| 14\" FHD IPS\nRam\t| 16 GB\nSSD\t| 512 GB\nHDD\t| 0\nWeight\t| 3.31 Lbs.\nBattery life\t| 8.5 Hrs.\nPros\t| USB-C charging.\nPros\t| Very light with a very powerful 8-core CPU.\nPros\t| Great battery life and weight.\n\nYou can also check my post about [Black Friday and Cyber Monday 2023 deals](\n\nPlease note I'm using affiliate links which means I'll receive a small percentage of the purchase if you use this link!",
            "Hi, I’m Vetted AI Bot! I researched the **Acer Swift X SFX14 41G R1S6 Creator Laptop 14 Full HD 100 sRGB AMD Ryzen 7 5800U NVIDIA RTX 3050Ti GPU 16GB LPDDR4X 512GB SSD Wi Fi 6 Backlit KB Amazon Alexa Windows 10 Home** you mentioned in your comment along with its brand, **Acer**, and I thought you might find the following analysis helpful.\n\n**Users liked:**\n* Laptop handles many tasks well (backed by 2 comments)\n* Good for students and programming (backed by 2 comments)\n* Fast and compact (backed by 2 comments)\n\n**Users disliked:**\n* The laptop has a short battery life (backed by 2 comments)\n* The laptop has hardware issues (backed by 2 comments)\n* The laptop has a poor keyboard (backed by 2 comments)\n\nAccording to Reddit, **Acer** is considered a reputable brand.  \nIts most popular types of products are:\n* Laptops (#5 of 40 brands on Reddit)\n* Monitors (#9 of 36 brands on Reddit)\n* Desktop Computers (#10 of 24 brands on Reddit)\n\n\nIf you'd like to **summon me to ask about a product**, just make a post with its link and tag me, [like in this example.]( \n\nThis message was generated by a (very smart) bot. If you found it helpful, let us know with an upvote and a “good bot!” reply and please feel free to provide feedback on how it can be improved.\n\n *Powered by* [*vetted.ai*]("
        ],
        "image": null,
        "name": "Acer Swift X 14 SFX14-71G",
        "price": 5999,
        "score": 69.42513399638209,
        "total_comments": 4,
        "total_upvotes": 4
    },
     {
        id" : 1,
        "average_thread_similarity": 0.5374293176306764,
        "comments": [
            "I recently got a MSI GF63 thin i5 11400H gtx1650Maxq 4gb for $530 and it's doing really well for me 35 fps in read dead 2 with \"Xbox one x\" settings, 60 fps in halo infinite one a mix of low and medium and most importantly to me It crushes beamNG drive at high settings. Although mine is running 24gbs of ram that was a upgrade"
        ],
        "image": "https://technave.com/data/files/article/small_202310240733106507.jpg",
        "name": "MSI Thin GF63 12UC",
        "price": 3399,
        "score": 32.18573294076691,
        "total_comments": 1,
        "total_upvotes": 1
    }
}